highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
#paginate: 5
port: 4000
safe: true
url: http://biomadeira.github.io/resume
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /resume/
title: Fábio Madeira's Resume
name: Fábio Madeira
email: fabiomadeira@me.com
email_full: mailto:fabiomadeira@me.com
website: biomadeira.github.io
github: biomadeira
twitter: biomadeira
tel: +44 7450 223192
tel_full: tel:+447450223192
google_maps: 'https://www.google.co.uk/maps/place/14+Gowrie+St,+Dundee,+Dundee+City+DD2+1ES'
address: 14 Gowrie Street
postcode: DD2 1ES
city: Dundee
country: United Kingdom
google_analytics: G-NWT1WS5QCK
